// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {dto} from '../models';

export function Close(arg1:number):Promise<api.Response_bool_>;

export function Create(arg1:dto.CreateConnectionRequest):Promise<api.Response_cyancat_internal_adapter_dto_ConnectionDTO_>;

export function Delete(arg1:number):Promise<api.Response_bool_>;

export function GetByID(arg1:number):Promise<api.Response_cyancat_internal_adapter_dto_ConnectionDTO_>;

export function List(arg1:dto.ListConnectionRequest):Promise<api.Response___cyancat_internal_adapter_dto_ConnectionDTO_>;

export function Open(arg1:number):Promise<api.Response_cyancat_internal_adapter_dto_ConnectionDTO_>;

export function Page(arg1:dto.PageConnectionRequest):Promise<api.Response_cyancat_internal_infra_api_Page_cyancat_internal_adapter_dto_ConnectionDTO__>;

export function Test(arg1:dto.TestConnectionRequest):Promise<api.Response_cyancat_internal_adapter_dto_TestConnectionResultDTO_>;

export function Update(arg1:number,arg2:dto.UpdateConnectionRequest):Promise<api.Response_cyancat_internal_adapter_dto_ConnectionDTO_>;
