// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['http']['ConnectionAPI']['Close'](arg1);
}

export function Create(arg1) {
  return window['go']['http']['ConnectionAPI']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['http']['ConnectionAPI']['Delete'](arg1);
}

export function GetByID(arg1) {
  return window['go']['http']['ConnectionAPI']['GetByID'](arg1);
}

export function List(arg1) {
  return window['go']['http']['ConnectionAPI']['List'](arg1);
}

export function Open(arg1) {
  return window['go']['http']['ConnectionAPI']['Open'](arg1);
}

export function Page(arg1) {
  return window['go']['http']['ConnectionAPI']['Page'](arg1);
}

export function Test(arg1) {
  return window['go']['http']['ConnectionAPI']['Test'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['http']['ConnectionAPI']['Update'](arg1, arg2);
}
