// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {api} from '../models';

export function ExportCSV(arg1:dto.ExportCSVRequest):Promise<api.Response_cyancat_internal_adapter_dto_ExportCSVResult_>;
