// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCSV(arg1) {
  return window['go']['http']['ExportAPI']['ExportCSV'](arg1);
}
