// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['http']['QueryAPI']['Cancel'](arg1);
}

export function Execute(arg1) {
  return window['go']['http']['QueryAPI']['Execute'](arg1);
}

export function History(arg1) {
  return window['go']['http']['QueryAPI']['History'](arg1);
}
