// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {dto} from '../models';

export function Cancel(arg1:number):Promise<api.Response_bool_>;

export function Execute(arg1:dto.ExecuteQueryRequest):Promise<api.Response_cyancat_internal_adapter_dto_QueryResultDTO_>;

export function History(arg1:dto.QueryHistoryRequest):Promise<api.Response_cyancat_internal_infra_api_Page_cyancat_internal_adapter_dto_QueryHistoryDTO__>;
