// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlterTable(arg1) {
  return window['go']['http']['SchemaAPI']['AlterTable'](arg1);
}

export function CreateDatabase(arg1) {
  return window['go']['http']['SchemaAPI']['CreateDatabase'](arg1);
}

export function CreateTable(arg1) {
  return window['go']['http']['SchemaAPI']['CreateTable'](arg1);
}

export function DescribeTable(arg1, arg2, arg3, arg4) {
  return window['go']['http']['SchemaAPI']['DescribeTable'](arg1, arg2, arg3, arg4);
}

export function GetCreateTableDDL(arg1) {
  return window['go']['http']['SchemaAPI']['GetCreateTableDDL'](arg1);
}

export function ListCharsets(arg1) {
  return window['go']['http']['SchemaAPI']['ListCharsets'](arg1);
}

export function ListCollations(arg1) {
  return window['go']['http']['SchemaAPI']['ListCollations'](arg1);
}

export function ListDatabases(arg1) {
  return window['go']['http']['SchemaAPI']['ListDatabases'](arg1);
}

export function ListSchemas(arg1, arg2) {
  return window['go']['http']['SchemaAPI']['ListSchemas'](arg1, arg2);
}

export function ListTables(arg1, arg2, arg3) {
  return window['go']['http']['SchemaAPI']['ListTables'](arg1, arg2, arg3);
}

export function ListViews(arg1, arg2, arg3) {
  return window['go']['http']['SchemaAPI']['ListViews'](arg1, arg2, arg3);
}

export function PreviewAlterTable(arg1) {
  return window['go']['http']['SchemaAPI']['PreviewAlterTable'](arg1);
}

export function PreviewCreateTable(arg1) {
  return window['go']['http']['SchemaAPI']['PreviewCreateTable'](arg1);
}
