// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DescribeTable(arg1, arg2, arg3, arg4) {
  return window['go']['http']['SchemaAPI']['DescribeTable'](arg1, arg2, arg3, arg4);
}

export function ListDatabases(arg1) {
  return window['go']['http']['SchemaAPI']['ListDatabases'](arg1);
}

export function ListSchemas(arg1, arg2) {
  return window['go']['http']['SchemaAPI']['ListSchemas'](arg1, arg2);
}

export function ListTables(arg1, arg2, arg3) {
  return window['go']['http']['SchemaAPI']['ListTables'](arg1, arg2, arg3);
}

export function ListViews(arg1, arg2, arg3) {
  return window['go']['http']['SchemaAPI']['ListViews'](arg1, arg2, arg3);
}
