// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function DescribeTable(arg1:number,arg2:string,arg3:string,arg4:string):Promise<api.Response_cyancat_internal_adapter_dto_TableDetailDTO_>;

export function ListDatabases(arg1:number):Promise<api.Response___cyancat_internal_adapter_dto_DatabaseDTO_>;

export function ListSchemas(arg1:number,arg2:string):Promise<api.Response___cyancat_internal_adapter_dto_SchemaDTO_>;

export function ListTables(arg1:number,arg2:string,arg3:string):Promise<api.Response___cyancat_internal_adapter_dto_TableDTO_>;

export function ListViews(arg1:number,arg2:string,arg3:string):Promise<api.Response___cyancat_internal_adapter_dto_ViewDTO_>;
