// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {api} from '../models';

export function AlterTable(arg1:dto.AlterTableRequest):Promise<api.Response_bool_>;

export function CreateDatabase(arg1:dto.CreateDatabaseRequest):Promise<api.Response_bool_>;

export function CreateTable(arg1:dto.CreateTableRequest):Promise<api.Response_bool_>;

export function DescribeTable(arg1:number,arg2:string,arg3:string,arg4:string):Promise<api.Response_cyancat_internal_adapter_dto_TableDetailDTO_>;

export function GetCreateTableDDL(arg1:dto.GetCreateTableDDLRequest):Promise<api.Response_string_>;

export function ListCharsets(arg1:dto.ListCharsetsRequest):Promise<api.Response___cyancat_internal_adapter_dto_CharsetDTO_>;

export function ListCollations(arg1:dto.ListCollationsRequest):Promise<api.Response___cyancat_internal_adapter_dto_CollationDTO_>;

export function ListDatabases(arg1:number):Promise<api.Response___cyancat_internal_adapter_dto_DatabaseDTO_>;

export function ListSchemas(arg1:number,arg2:string):Promise<api.Response___cyancat_internal_adapter_dto_SchemaDTO_>;

export function ListTables(arg1:number,arg2:string,arg3:string):Promise<api.Response___cyancat_internal_adapter_dto_TableDTO_>;

export function ListViews(arg1:number,arg2:string,arg3:string):Promise<api.Response___cyancat_internal_adapter_dto_ViewDTO_>;

export function PreviewAlterTable(arg1:dto.AlterTableRequest):Promise<api.Response_string_>;

export function PreviewCreateTable(arg1:dto.CreateTableRequest):Promise<api.Response_string_>;
